name: Migrate Preview Database

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  migrate-preview:
    name: Run Preview Migrations
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run db:generate

      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Verify migration status
        run: npx prisma migrate status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Comment PR with migration status
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const status = '${{ job.status }}';
            const body = status === 'success' 
              ? '✅ Preview database migrations completed successfully!'
              : '❌ Preview database migrations failed. Please check the logs.';

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body
            });
